version: "3.8"

services:
  h2-database:
    image: oscarfonts/h2
    container_name: h2-database
    ports:
      - "8082:8082"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      H2_OPTIONS: "-ifNotExists"
    command: -webAllowOthers -tcpAllowOthers -ifNotExists -tcp -tcpPort 9092
